INSERT INTO games (name, slug, description, publisher_id, original_price, sale_price, is_sale, release_date, created_at, updated_at) VALUES
("Deity of Conflict","deity-of-conflict","Kratos is a father again. As mentor and protector to Atreus, a son determined to earn his respect, he is forced to deal with and control the rage that has long defined him while out in a very dangerous world with his son. His vengeance against the Gods of Olympus behind him, Kratos now lives in the realm of Norse deities and monsters. Its in this harsh, unforgiving world that he must fight to survive, and not only teach his son to do the same… but also prevent him from repeating the Ghost of Spartas bloodstained mistakes. This staggering reimagining of Deity of Conflict combines all the hallmarks of the iconic series brutal combat, epic boss fights, and breathtaking scale  and fuses them with a powerful and moving narrative that re-establishes Kratos world. ", 1,59.99 ,29.99 ,true,"2018-04-20",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Velocity Vista 5","velocity-vista-5","
    Lead breathtaking expeditions across the open world landscape of Mexico in Velocity Vista 5. This vibrant and ever evolving terrain offers limitless driving action in the worlds greatest cars. Velocity Vista 5 offers an immersive, deep campaign with hundreds of challenges and rewards for doing what you love. Team up with other players around the world in the Vista arcade and engage in epic, fun and over the top challenges, keeping you and your friends having driving fun, with no load screens or lobbies. 
    ",2,59.99,53.99,true,"2021-11-04",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Battle Cry: Modern Warfare","battle-cry-modern-warfare","
    The stakes have never been higher as players take on the role of lethal Tier One operators in a heart-racing saga that will affect the global balance of power. Battle Cry: Modern Warfare engulfs fans in an incredibly raw, gritty, provocative narrative that brings unrivaled intensity and shines a light on the changing nature of modern war. Developed by the studio that started it all, Infinity Ward delivers an epic reimagining of the iconic Modern Warfare® series from the ground up. In the visceral and dramatic single-player story campaign, Battle Cry: Modern Warfare pushes boundaries and breaks rules the way only Modern Warfare can. Players will engage in breathtaking covert operations alongside a diverse cast of international special forces and freedom fighters throughout iconic European cities and volatile expanses of the Middle East. And the story doesn't end there. In Battle Cry: Modern Warfare, players will be thrust into an immersive narrative spanning the entire game. Experience the ultimate online playground with classic multiplayer, or squad-up and play cooperatively in a collection of elite operations accessible to all skill levels.
    ",3,59.99,44.99,false,"2019-10-25",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Warfront 2041","warfront-2041","
    Warfront 2041 is multiplayer focused and has no singleplayer campaign, the first main series entry to not include one since Warfront 2041. However, similar to older entries in the series like Warfront, players will have the option of playing against AI bots in either solo or co-op modes, although the game is always online and cannot be played offline. Certain multiplayer modes like Conquest and Breakthrough will support up to 128 players per server on ninth generation consoles and PC, the first Warfront game to officially support over 100 players in a single match since the Korean exclusive Warfront Online. The Playstation 4 and Xbox One versions of 2041 will only support up to 64 players with smaller scale maps.
    ",4,59.99,39.99,false,"2021-11-19",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Criminal Empire","criminal-empire","
    When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.

Criminal Empire for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.

The game offers players a huge range of PC-specific customization options, including over 25 separate configurable settings for texture quality, shaders, tessellation, anti-aliasing and more, as well as support and extensive customization for mouse and keyboard controls. Additional options include a population density slider to control car and pedestrian traffic, as well as dual and triple monitor support, 3D compatibility, and plug-and-play controller support.

Criminal Empire for PC also includes Criminal Empire Online, with support for 30 players and two spectators. Criminal Empire Online for PC will include all existing gameplay upgrades and Criminal Empire-created content released since the launch of Criminal Empire Online, including Heists and Adversary modes.

The PC version of Criminal Empire and Criminal Empire Online features First Person Mode, giving players the chance to explore the incredibly detailed world of Los Santos and Blaine County in an entirely new way.

Criminal Empire for PC also brings the debut of the Criminal Empire Editor, a powerful suite of creative tools to quickly and easily capture, edit and share game footage from within Criminal Empire and Criminal Empire Online. The Criminal Empire Editors Director Mode allows players the ability to stage their own scenes using prominent story characters, pedestrians, and even animals to bring their vision to life. Along with advanced camera manipulation and editing effects including fast and slow motion, and an array of camera filters, players can add their own music using songs from Criminal Empire radio stations, or dynamically control the intensity of the games score. Completed videos can be uploaded directly from the Criminal Empire Editor to YouTube and the  for easy sharing. 
    ",5,29.99,14.99,true,"2013-9-17",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("European Hauler","european-hauler","
    European Hauler gives you the chance to become a real truck driver from the comfort of your home! Featuring licensed trucks with countless customization options and advanced driving physics, the game delivers an unparalleled driving experience which has put it in the spot of the most popular truck driving simulator on the market. In game world features numerous landmarks and precisely recreated territories to create the ultimate experience, making you feel as if you were driving the trucks in real life! But let's not be fooled - European Hauler is not only about driving - the economy in game allows you to create and grow your own transportation company exactly as you see fit - the opportunities are endless! 
    ",6,19.99,4.99,true,"2012-10-19",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Realm Wanderer","realm-wanderer","
    The game takes place in a fictional fantasy world based on Slavic mythology. Players control Wanderer of Rivia, a monster slayer for hire known as a Wanderer, and search for his adopted daughter, who is on the run from the otherworldly Wild Hunt. Players battle the game's many dangers with weapons and magic, interact with non-player characters, and complete quests to acquire experience points and gold, which are used to increase Wanderer's abilities and purchase equipment. The game's story has three possible endings, determined by the player's choices at key points in the narrative. 
    ",7,29.99,5.99,false,"2015-05-18",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Medieval Glory","medieval-glory","
    Medieval Glory is an action role-playing game set in an open-world environment and played from a first-person perspective. It utilizes a classless role-playing system, allowing the player to customize their skills to take on roles such as warrior, bard, thief, or a hybrid of these. Abilities and stats grow depending on what the player does and says through branched dialogue trees. During conversations, the time a player takes to make a decision is limited and has an effect on their relationships with others. Reputation is based on player choices and therefore can bring consequences.

Character bodies and faces are created through the combination of multiple, individual pieces with finishing touches. The clothing system features 16 item slots and items on many areas of the body that can be layered. For example, a heavily armored knight may on his upper body wear a gambeson, followed by mail and plate armour, with a tabard or surcoat over top, for a total of four clothing items in the chest slots. Each clothing type provides different levels of protection against different types of weapons. Clothing also gets progressively more worn, dirty, or bloody through use, affecting the character's appearance. The player is able to use a variety of weapons, including swords, knives, axes, hammers, and bows. Horses are featured heavily in the game, and are designed to act with their own AI while under the player's control, moving or jumping to avoid small obstacles or dangers. The player can also fight from horseback and use their steed to carry items if they need additional inventory space, but warhorses are also competent combatants with their own AI. Steeds come with five slots for armor and attachments. 
    ",8,29.99,7.99,true,"2018-02-13",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Fearful Village","fearful-village","
    Experience survival horror like never before in the eighth major installment in the storied Resident Evil franchise - Resident Evil Village.

Set a few years after the horrifying events in the critically acclaimed Resident Evil 7 biohazard, the all-new storyline begins with Ethan Winters and his wife Mia living peacefully in a new location, free from their past nightmares. Just as they are building their new life together, tragedy befalls them once again.
    ",9,59.99,43.99,true,"2021-05-01",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Elite Combat Operations","elite-combat-operations","
    Elite Combat Operations expands upon the team-based first person shooter gameplay the original Elite Combat pioneered when it launched in 1999. Two teams compete in multiple rounds of objective-based game modes with the goal of winning enough rounds to win the match.

Elite Combat Operations features new maps, characters, and weapons and delivers updated versions of the classic Elite Combat maps like Dust, Inferno, Nuke, Train, and more. In addition, Elite Combat Operations introduces new game modes like Arms Race, Flying Scoutsman and Wingman, and features online matchmaking and Competitive Skill Groups.
    ",10,0,0,false,"2012-08-21",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Demonic Apocalypse","demonic-apocalypse","
    Players once again take on the role of the Demonic Slayer who battles the demonic forces of Hell, from a first-person perspective. The game continues its predecessor's emphasis on push-forward combat, encouraging the player to aggressively engage enemies in order to acquire health, ammo, and armor. The player has access to various firearms, such as the Combat Shotgun, Super Shotgun, Heavy Cannon, Rocket Launcher, Plasma Rifle, Chaingun, BFG 9000, and Ballista. Melee weapons such as a chainsaw, the Crucible Blade energy sword, the Sentinel Argent Hammer, and a retractable arm-blade called the Demonicblade can also be used. The arm-blade provides the opportunity for a larger variety of quick and violent glory kill executions, which drop extra health. The Super Shotgun is now equipped with the Meat Hook, a ranged accessory which grabs on to enemies and slingshots the player towards them, functioning as a grappling hook, useful both in combat scenarios and environmental navigation. The Demonic Slayer's armor now includes a shoulder-mounted Equipment Launcher with the ability to lob grenades and ice bombs. In addition, there is the Flame Belch, a flamethrower that sets enemies on fire with it to drop armor pickups. Finally, killing enemies with the chainsaw will drop ammunition. New movement mechanics such as wall-climbing, dash moves, and horizontal bars to swing from have also been introduced.
    ",11,59.99,29.99,true,"2020-03-20",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Tactical Siege Operations","tactical-siege-operations","
    Tactical Siege Operations is a first-person shooter game, in which players utilize many different operators from the Rainbow team. Different operators have different nationalities, weapons, and gadgets. The game features an asymmetrical structure whereby the teams are not always balanced in their choices of abilities. The base Counter-Terrorism Units (CTUs) available for play are the American Hostage Rescue Team (referred to in-game as the FBI SWAT), the British SAS, the German GSG-9, the Russian Spetsnaz and the French GIGN, each of which has four operators per unit split between attackers and defenders (other units were later added through downloadable content, see below). Players also have access to a  Recruit operator who can choose from a more flexible assortment of equipment at the expense of having a unique gadget or the ability to customize their weapon. Players can pick any operator from any unit that is defending or attacking before a round starts, choosing spawn points as well as attachments on their guns but are not allowed to change their choices once the round has started. An in-game shop allows players to purchase operators or cosmetics using the in-game currency, Renown, which is earned at the end of matches from actions performed in-game. Different gameplay modes award renown at different rates, with ranked matches offering the largest renown multiplier potential per match. Players can also complete in-game challenges to get a small amount of renown. Renown gain rate can also be affected by the using in-game boosters which gives the player an increase in all renown earned for various duration, starting with 24 hours. A premium currency known as R6 credits can also be purchased using real-world currency to get operators quicker in-game, or other cosmetic items, such as weapon or operator skins .
    ",12,29.99,15.99,false,"2015-11-26",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Tank Warfare","tank-warfare","
    The player takes control of a single armored tank or self-propelled artillery vehicle of their choice, and is placed into a battle on a random map. The player has control over the vehicle's movement, firing, and can communicate with allied players and all the other players through typed or voice chat. A simple random match is won either by destroying all vehicles on the opposing team or capturing the opposing team's base by staying in it for long enough without being damaged by another tank. There are other game modes that change the rules of the battle, but gameplay mechanics remain the same. Tank Warfare contains multiple game mechanics such as camouflage, shell ricochets, and module and personnel damage.

The players in Tank Warfare can choose six primary types of battles: random battles, team-training battles, tank-company battles, team battles, stronghold battles and special battles. Historical Battle and Rampage are former options but have since been taken down for improvement due to poor reception following their releases. Within random battles, players can also participate in platoons, groups of two or three players who are put into the same team. There are also missions to be completed in the game modes for varying amounts of rewards. A random battle includes up to 15v15 players; bots may be used to fill gaps. 
    ",13,0,0,false,"2010-08-12",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Last Man Standing","last-man-standing","
    At a fundamental level, Last Man Standing is about tense and realistic gunplay and advancement by looting. Sporting a massive selection of guns and modifications, along with a realistic ballistics model, death in the game can come quickly and painfully. Adding to the realism, weapons need to be cared for lest they wear out and jam or overheat. Similarly, players will need to tend to their own health as bones break, wounds bleed, and exhaustion sets in. This is not a game for the timid!
    ",14,129.99,98.99,false,"2016-08-04",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
("Block Crafters","block-crafters","
    Block Crafters is a 3D sandbox game that has no required goals to accomplish, allowing players a large amount of freedom in choosing how to play the game. However, there is an achievement system, known as advancements in the Java Edition of the game, and trophies on the PlayStation ports. Gameplay is in the first-person perspective by default, but players have the option for third-person perspective. The game world is composed of rough 3D objects—mainly cubes and fluids, and commonly called blocks—representing various materials, such as dirt, stone, ores, tree trunks, water, and lava. The core gameplay revolves around picking up and placing these objects. These blocks are arranged in a 3D grid, while players can move freely around the world. Players can mine blocks and then place them elsewhere, enabling them to build things. Many commentators have described the game's physics system as unrealistic. The game also contains a material called redstone, which can be used to make primitive mechanical devices, electrical circuits, and logic gates, allowing for the construction of many complex systems.
    ",15,24.99,13.99,false,"2011-11-18",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)